-- 코드를 입력하세요
SELECT PRO.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRO JOIN FOOD_ORDER AS ORD ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID;