-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE MEM JOIN REST_REVIEW REV ON MEM.MEMBER_ID = REV.MEMBER_ID
WHERE MEM.MEMBER_ID = (SELECT MEMBER_ID
                       FROM REST_REVIEW
                       GROUP BY MEMBER_ID
                       ORDER BY COUNT(MEMBER_ID) DESC
                       LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;