-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, MIN(DAILY_FEE * (100 - NVL(DISCOUNT_RATE, 0)) / 100 * 30) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS 
     LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR ON HIS.CAR_ID = CAR.CAR_ID
     LEFT JOIN (SELECT *
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE DURATION_TYPE = '30일 이상') DIS 
        ON CAR.CAR_TYPE = DIS.CAR_TYPE 
WHERE CAR.CAR_TYPE IN ('세단', 'SUV') AND
      CAR.CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE START_DATE < TO_DATE('20221130', 'YYYYMMDD') AND
                               END_DATE > TO_DATE('20221101', 'YYYYMMDD'))
GROUP BY CAR.CAR_ID, CAR.CAR_TYPE
HAVING MIN(DAILY_FEE * (100 - NVL(DISCOUNT_RATE, 0)) / 100 * 30) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;