-- 코드를 입력하세요
SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, SUM(PRO.PRICE * ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO JOIN FOOD_ORDER ORD ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY PRO.PRODUCT_ID, PRO.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID;