-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, MIN(ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30)) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
     LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR ON HIS.CAR_ID = CAR.CAR_ID
     LEFT JOIN (SELECT * 
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE DURATION_TYPE = '30일 이상') DIS ON CAR.CAR_TYPE = DIS.CAR_TYPE
WHERE CAR.CAR_TYPE IN ('세단', 'SUV') AND
      CAR.CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE START_DATE < '2022-11-30' AND
                               END_DATE > '2022-11-01')
GROUP BY CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;