-- 코드를 작성해주세요
WITH SUM_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO)

SELECT SUM_SCORE.SCORE, EMP.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES EMP JOIN SUM_SCORE ON EMP.EMP_NO = SUM_SCORE.EMP_NO
WHERE SUM_SCORE.SCORE IN (SELECT MAX(SCORE)
                          FROM SUM_SCORE);