-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT FLAVOR, TOTAL_ORDER
      FROM FIRST_HALF
      UNION
      SELECT FLAVOR, TOTAL_ORDER
      FROM JULY)
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
FETCH NEXT 3 ROWS ONLY;