-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
FROM BOOK LEFT JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
          LEFT JOIN BOOK_SALES SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, CATEGORY
ORDER BY 1, CATEGORY DESC;