-- 코드를 작성해주세요
SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA ECO JOIN (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
                          FROM ECOLI_DATA
                          GROUP BY YEAR) MAX_ECO
                    ON YEAR(ECO.DIFFERENTIATION_DATE) = MAX_ECO.YEAR
ORDER BY YEAR, YEAR_DEV;