-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
                                ON CAR.CAR_ID = HIS.CAR_ID
WHERE CAR_TYPE = '세단' AND TO_CHAR(START_DATE, 'YY-MM') = '22-10'
ORDER BY 1 DESC;