-- 코드를 입력하세요
SELECT TIME.HOUR AS HOUR, COUNT(ANI.DATETIME) AS COUNT
FROM (SELECT LEVEL - 1 HOUR
      FROM DUAL
      CONNECT BY LEVEL <= 24) TIME LEFT JOIN ANIMAL_OUTS ANI
          ON TIME.HOUR = TO_NUMBER(TO_CHAR(ANI.DATETIME, 'HH24'))
WHERE TIME.HOUR BETWEEN 0 AND 23
GROUP BY TIME.HOUR
ORDER BY TIME.HOUR;