-- 코드를 입력하세요
SELECT '/home/grep/src/'||BOA.BOARD_ID||'/'||FILE_ID||FILE_NAME||FILE_EXT FILE_PATH
FROM USED_GOODS_BOARD BOA LEFT JOIN USED_GOODS_FILE FIL ON BOA.BOARD_ID = FIL.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS)
               FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;