-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR, EXTRACT(MONTH FROM SALES_DATE) MONTH, 
       GENDER, COUNT(DISTINCT INFO.USER_ID) USERS
FROM USER_INFO INFO JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;