-- 코드를 작성해주세요
SELECT ECO.ID AS ID, ECO.GENOTYPE AS GENOTYPE, PAR.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ECO JOIN (SELECT ID, GENOTYPE
                          FROM ECOLI_DATA) PAR ON ECO.PARENT_ID = PAR.ID
WHERE ECO.GENOTYPE & PAR.GENOTYPE = PAR.GENOTYPE
ORDER BY ID;