-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ECO.ID, CTE.GENERATION + 1
    FROM ECOLI_DATA ECO JOIN CTE ON ECO.PARENT_ID = CTE.ID)
    
SELECT COUNT(ECO.ID) COUNT, GENERATION
FROM ECOLI_DATA ECO JOIN CTE ON ECO.ID = CTE.ID
WHERE ECO.ID NOT IN (SELECT PARENT_ID 
                     FROM ECOLI_DATA
                     WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;