-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) TOTAL_SALES
FROM AUTHOR LEFT JOIN BOOK ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
            LEFT JOIN BOOK_SALES SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;