-- 코드를 입력하세요
SELECT BO.TITLE, BO.BOARD_ID, RE.REPLY_ID, RE.WRITER_ID, RE.CONTENTS, DATE_FORMAT(RE.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD BO JOIN USED_GOODS_REPLY RE ON BO.BOARD_ID = RE.BOARD_ID
WHERE BO.CREATED_DATE LIKE '2022-10%'
ORDER BY RE.CREATED_DATE, BO.TITLE;