-- 코드를 작성해주세요
SELECT CASE WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND
                 SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'A'
            WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C'
       END AS GRADE, ID, EMAIL
FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND
       SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) OR
      SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') OR
      SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')
ORDER BY GRADE, ID;