-- 코드를 입력하세요
SELECT HISTORY_ID, MIN(DAILY_FEE * (100 - NVL(DISCOUNT_RATE, 0)) / 100 * (END_DATE - START_DATE + 1)) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS 
     LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR ON HIS.CAR_ID = CAR.CAR_ID
     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DIS 
        ON CAR.CAR_TYPE = DIS.CAR_TYPE AND 
           END_DATE - START_DATE + 1 >= REGEXP_REPLACE(DURATION_TYPE, '[^0-9]')
WHERE CAR.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY 2 DESC, 1 DESC;