-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) MONTH, CAR_ID, COUNT(CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN TO_DATE('220801', 'YYMMDD') AND TO_DATE('221031', 'YYMMDD')
                 GROUP BY CAR_ID
                 HAVING COUNT(CAR_ID) >= 5)
      AND START_DATE BETWEEN TO_DATE('220801', 'YYMMDD') AND TO_DATE('221031', 'YYMMDD')
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY 1, 2 DESC;