-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO INFO JOIN FISH_NAME_INFO NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE INFO.FISH_TYPE IN (SELECT FISH_TYPE
                         FROM FISH_INFO
                         GROUP BY FISH_TYPE
                         HAVING LENGTH = MAX(LENGTH))
ORDER BY ID;