-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO INFO JOIN FISH_NAME_INFO NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE LENGTH IN (SELECT MAX(LENGTH)
                 FROM FISH_INFO INFO2
                 WHERE INFO.FISH_TYPE = INFO2.FISH_TYPE
                 GROUP BY FISH_TYPE
                 HAVING LENGTH = MAX(LENGTH))
ORDER BY ID;