-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ECO.ID, CTE.GEN + 1
    FROM ECOLI_DATA ECO JOIN CTE ON ECO.PARENT_ID = CTE.ID
    WHERE CTE.GEN <= 3)
    
SELECT ID
FROM CTE
WHERE GEN = 3
ORDER BY ID;